package net.elytrarace.voyager.physics.trace;

import net.elytrarace.voyager.api.math.Aabb;
import net.elytrarace.voyager.api.math.Vec3;
import net.elytrarace.voyager.api.physics.CollisionSpace;
import net.elytrarace.voyager.api.physics.FlightInput;
import net.elytrarace.voyager.api.physics.FlightState;
import net.elytrarace.voyager.physics.ElytraSimulator;
import net.elytrarace.voyager.physics.trace.TraceReplay.ReplayReport;
import net.elytrarace.voyager.physics.trace.exception.InvalidReplayThresholdException;
import net.elytrarace.voyager.physics.trace.exception.InvalidTraceFixtureException;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assertions.within;

/**
 * Proves the trace replay harness against synthetic fixtures generated by running {@link
 * ElytraSimulator} itself, since no real Vanilla recording exists until E2a completes (see
 * {@code docs/superpowers/plans/2026-09-10-e2a-trace-recorder.md}). A fixture built this way and
 * replayed with zero divergence proves the harness is correct before it is ever pointed at a real
 * recording — a later red trace then means the physics port is wrong, not that the harness might
 * be.
 */
class TraceReplayTest {

    /**
     * Deliberately not Vanilla's 0.08 default: a replay that hardcodes 0.08 instead of reading
     * {@link TraceFixture.Metadata#gravity()} diverges from every fixture built with this value.
     */
    private static final double GRAVITY = 0.05;

    private static final CollisionSpace FREE_FLIGHT = CollisionSpace.empty();

    // ---- fixture construction helpers --------------------------------------------------------

    private static FlightState seed() {
        return new FlightState(new Vec3(0, 100, 0), new Vec3(0.3, -0.2, 0.5), 0.0f, -20.0f, false);
    }

    private static List<FlightInput> constantInputs(int count, float yaw, float pitch) {
        List<FlightInput> inputs = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            inputs.add(new FlightInput(yaw, pitch, false, 0, GRAVITY));
        }
        return inputs;
    }

    /**
     * Rotation that changes on every tick, so a replay that reads tick {@code i - 1}'s rotation
     * instead of tick {@code i}'s feeds a different look vector into every step. The range stays
     * clear of ±90, where {@code lookHorLength} degenerates.
     */
    private static List<FlightInput> varyingInputs(int count) {
        List<FlightInput> inputs = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            inputs.add(new FlightInput(-30.0f + i * 7.0f, -25.0f + i * 3.0f, false, 0, GRAVITY));
        }
        return inputs;
    }

    /**
     * A boost window: inactive, then active for {@code boostLength} consecutive ticks with the
     * remaining-tick counter running down, then inactive again. No other fixture in this class ever
     * sets {@code fireworkBoostActive} — {@link #constantInputs} hardcodes {@code false, 0} — even
     * though the parity profiles include a single boost and chained boosts.
     */
    private static List<FlightInput> boostWindowInputs(int count, int boostStart, int boostLength) {
        List<FlightInput> inputs = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            boolean boosting = i >= boostStart && i < boostStart + boostLength;
            int remaining = boosting ? boostStart + boostLength - i : 0;
            inputs.add(new FlightInput(0.0f, -20.0f, boosting, remaining, GRAVITY));
        }
        return inputs;
    }

    private static TraceFixture.Tick tickOf(FlightState state, boolean boostActive, int boostTicks) {
        return new TraceFixture.Tick(
                0,
                state.position().x(), state.position().y(), state.position().z(),
                state.velocity().x(), state.velocity().y(), state.velocity().z(),
                state.yaw(), state.pitch(),
                state.onGround(),
                boostActive, boostTicks);
    }

    private static TraceFixture.Tick withIndex(TraceFixture.Tick tick, int index) {
        return new TraceFixture.Tick(
                index,
                tick.posX(), tick.posY(), tick.posZ(),
                tick.velX(), tick.velY(), tick.velZ(),
                tick.yaw(), tick.pitch(),
                tick.onGround(), tick.fireworkBoostActive(), tick.fireworkTicksRemaining());
    }

    /** Runs {@link ElytraSimulator#tick} forward and records every tick in fixture format. */
    private static TraceFixture generateFixture(
            FlightState seed, List<FlightInput> inputs, CollisionSpace space, List<TraceFixture.BlockBox> worldSlice) {
        List<TraceFixture.Tick> ticks = new ArrayList<>();
        ticks.add(withIndex(tickOf(seed, false, 0), 0));

        FlightState state = seed;
        for (int i = 0; i < inputs.size(); i++) {
            state = ElytraSimulator.tick(state, inputs.get(i), space);
            ticks.add(withIndex(tickOf(state, inputs.get(i).fireworkBoostActive(), inputs.get(i).fireworkTicksRemaining()), i + 1));
        }

        TraceFixture.Metadata metadata = new TraceFixture.Metadata("26.2", "synthetic", GRAVITY, 1, worldSlice);
        return new TraceFixture(metadata, ticks);
    }

    private static TraceFixture.Tick withPosition(TraceFixture.Tick tick, double dx) {
        return new TraceFixture.Tick(
                tick.index(),
                tick.posX() + dx, tick.posY(), tick.posZ(),
                tick.velX(), tick.velY(), tick.velZ(),
                tick.yaw(), tick.pitch(),
                tick.onGround(), tick.fireworkBoostActive(), tick.fireworkTicksRemaining());
    }

    private static TraceFixture.Tick withVelocity(TraceFixture.Tick tick, Vec3 velocity) {
        return new TraceFixture.Tick(
                tick.index(),
                tick.posX(), tick.posY(), tick.posZ(),
                velocity.x(), velocity.y(), velocity.z(),
                tick.yaw(), tick.pitch(),
                tick.onGround(), tick.fireworkBoostActive(), tick.fireworkTicksRemaining());
    }

    private static TraceFixture withTick(TraceFixture fixture, int index, TraceFixture.Tick replacement) {
        List<TraceFixture.Tick> ticks = new ArrayList<>(fixture.ticks());
        ticks.set(index, replacement);
        return new TraceFixture(fixture.metadata(), ticks);
    }

    // ---- clean replay --------------------------------------------------------------------------

    @Test
    void aSyntheticFixtureGeneratedFromTheSimulatorReplaysWithZeroDivergence() {
        TraceFixture fixture = generateFixture(seed(), constantInputs(30, 0.0f, -20.0f), FREE_FLIGHT, List.of());

        ReplayReport report = TraceReplay.replay(fixture);

        assertThat(report.isClean()).isTrue();
        assertThat(report.firstDivergingTick()).isEmpty();
        assertThat(report.finalDrift()).isEqualTo(0.0);
        assertThat(report.summedTickError()).isEqualTo(0.0);
        assertThat(report.driftThresholdExceeded()).isFalse();
    }

    @Test
    void aSyntheticFixtureWithCollisionAgainstAFloorReplaysWithZeroDivergence() {
        TraceFixture fixture = landingFixture();

        // Otherwise a change to the seed (e.g. a shallower fall) silently turns this into a
        // duplicate of the free-flight test above, without ever having exercised collision at all.
        assertThat(fixture.ticks().getLast().onGround()).isTrue();

        ReplayReport report = TraceReplay.replay(fixture);

        assertThat(report.isClean()).isTrue();
        assertThat(report.finalDrift()).isEqualTo(0.0);
        assertThat(report.summedTickError()).isEqualTo(0.0);
    }

    @Test
    void theJsonRoundTripPreservesASyntheticFixtureAndStillReplaysClean() {
        TraceFixture fixture = generateFixture(seed(), constantInputs(10, 0.0f, -20.0f), FREE_FLIGHT, List.of());

        String json = TraceFixtureLoader.toJson(fixture);
        TraceFixture restored = TraceFixtureLoader.fromJson(json);

        assertThat(restored).isEqualTo(fixture);
        assertThat(TraceReplay.replay(restored).isClean()).isTrue();
    }

    /** A short fall onto a floor, ending on the ground — shared by the collision-related tests. */
    private static TraceFixture landingFixture() {
        List<TraceFixture.BlockBox> worldSlice = List.of(new TraceFixture.BlockBox(-64, -1, -64, 64, 0, 64));
        CollisionSpace floor = region -> List.of(new Aabb(new Vec3(-64, -1, -64), new Vec3(64, 0, 64)));
        FlightState fallingSeed = new FlightState(new Vec3(0, 2, 0), new Vec3(0, -0.5, 0.2), 0.0f, 0.0f, false);
        return generateFixture(fallingSeed, constantInputs(15, 0.0f, 0.0f), floor, worldSlice);
    }

    // ---- each tick's input comes from that tick, not the one before it -----------------------

    /**
     * Every other fixture in this class uses constant rotation, so taking {@code yaw} and
     * {@code pitch} from {@code ticks.get(i - 1)} instead of {@code ticks.get(i)} produced identical
     * inputs and left the suite green — an off-by-one that would misread every real recording, where
     * the player is turning. With rotation changing on every tick the shift feeds a different look
     * vector into every step and the replay stops being clean.
     */
    @Test
    void aFixtureWithChangingRotationReplaysCleanOnlyWithTheRightTickAlignment() {
        TraceFixture fixture = generateFixture(seed(), varyingInputs(20), FREE_FLIGHT, List.of());

        // Otherwise a change to varyingInputs silently turns this into a constant-rotation duplicate.
        assertThat(fixture.ticks().get(1).yaw()).isNotEqualTo(fixture.ticks().get(2).yaw());
        assertThat(fixture.ticks().get(1).pitch()).isNotEqualTo(fixture.ticks().get(2).pitch());

        ReplayReport report = TraceReplay.replay(fixture);

        assertThat(report.isClean()).isTrue();
        assertThat(report.firstDivergingTick()).isEmpty();
    }

    /**
     * The same off-by-one on the boost fields. No fixture ever set {@code fireworkBoostActive}, so
     * shifting the boost window by one tick changed nothing measurable; here the window is five
     * ticks long and a one-tick shift applies the impulse on the wrong ticks.
     */
    @Test
    void aFixtureWithABoostWindowReplaysCleanOnlyWithTheRightTickAlignment() {
        TraceFixture fixture = generateFixture(seed(), boostWindowInputs(20, 5, 5), FREE_FLIGHT, List.of());

        // Otherwise a change to boostWindowInputs silently turns this into a no-boost duplicate.
        assertThat(fixture.ticks().stream().filter(TraceFixture.Tick::fireworkBoostActive)).hasSize(5);
        assertThat(fixture.ticks().get(5).fireworkBoostActive()).isFalse();
        assertThat(fixture.ticks().get(6).fireworkBoostActive()).isTrue();

        ReplayReport report = TraceReplay.replay(fixture);

        assertThat(report.isClean()).isTrue();
        assertThat(report.firstDivergingTick()).isEmpty();
    }

    // ---- naming the diverging tick ---------------------------------------------------------

    @Test
    void aPerturbedTickIsNamedRatherThanAnArbitraryOne() {
        TraceFixture clean = generateFixture(seed(), constantInputs(20, 0.0f, -20.0f), FREE_FLIGHT, List.of());
        int perturbedTick = 8;
        TraceFixture perturbed = withTick(clean, perturbedTick, withPosition(clean.ticks().get(perturbedTick), 0.25));

        ReplayReport report = TraceReplay.replay(perturbed, 0.01, 1000.0);

        assertThat(report.firstDivergingTick()).hasValue(perturbedTick);
    }

    @Test
    void theFirstDivergingTickIsReportedEvenWhenALaterTickDivergesMore() {
        TraceFixture clean = generateFixture(seed(), constantInputs(20, 0.0f, -20.0f), FREE_FLIGHT, List.of());
        double threshold = 0.01;
        int earlyTick = 5;
        int laterTick = 15;

        TraceFixture perturbed = withTick(clean, earlyTick, withPosition(clean.ticks().get(earlyTick), threshold + 0.001));
        perturbed = withTick(perturbed, laterTick, withPosition(perturbed.ticks().get(laterTick), threshold + 5.0));

        ReplayReport report = TraceReplay.replay(perturbed, threshold, 1000.0);

        assertThat(report.firstDivergingTick()).hasValue(earlyTick);
        assertThat(report.firstDivergingTickError()).isLessThan(5.0);
    }

    // ---- per-tick threshold boundary --------------------------------------------------------

    /**
     * Pins the boundary just below the threshold rather than exactly at it: the recorded position
     * here is built by adding a double to a value already computed by the simulator (position
     * magnitude ~100), and IEEE 754 addition of two such values is not guaranteed to round-trip
     * back to an error of exactly {@code threshold} on subtraction — the last bit or two can go
     * either way. A margin many orders of magnitude past that rounding noise (~1e-14 at this
     * magnitude) still pins the boundary tightly without the test depending on bit-exact rounding.
     */
    @Test
    void divergenceJustBelowThePerTickThresholdIsNotReported() {
        TraceFixture clean = generateFixture(seed(), constantInputs(10, 0.0f, -20.0f), FREE_FLIGHT, List.of());
        int tick = 4;
        double threshold = 0.25;
        TraceFixture perturbed = withTick(clean, tick, withPosition(clean.ticks().get(tick), threshold - 1.0E-9));

        ReplayReport report = TraceReplay.replay(perturbed, threshold, 1000.0);

        assertThat(report.firstDivergingTick()).isEmpty();
    }

    @Test
    void divergenceJustAboveThePerTickThresholdIsReportedAsAFailure() {
        TraceFixture clean = generateFixture(seed(), constantInputs(10, 0.0f, -20.0f), FREE_FLIGHT, List.of());
        int tick = 4;
        double threshold = 0.25;
        TraceFixture perturbed = withTick(clean, tick, withPosition(clean.ticks().get(tick), threshold + 1.0E-9));

        ReplayReport report = TraceReplay.replay(perturbed, threshold, 1000.0);

        assertThat(report.firstDivergingTick()).hasValue(tick);
    }

    // ---- drift at the final tick is independent of the per-tick bound -----------------------

    /**
     * {@code finalDrift} is the position error at the <em>last</em> tick — the spec's "cumulative
     * drift over 200 ticks", a single end-of-replay distance. A replay that never exceeds the
     * per-tick bound (so {@code firstDivergingTick} and {@code firstDivergingTickError} stay at
     * their empty/zero defaults) can still finish outside a tighter drift bound, proving the two
     * figures are tracked independently rather than one being derived from the other. A test that
     * only replays a clean fixture and finds both at {@code 0.0} cannot tell these apart from a
     * single field duplicated under two names; this one can, because only one of them trips.
     */
    @Test
    void aReplayStayingUnderThePerTickBoundButOverTheDriftBoundIsStillReported() {
        int tickCount = 25;
        TraceFixture clean = generateFixture(seed(), constantInputs(tickCount, 0.0f, -20.0f), FREE_FLIGHT, List.of());
        TraceFixture perturbed = withTick(clean, tickCount, withPosition(clean.ticks().get(tickCount), 0.1));

        double perTickThreshold = 0.5; // the final tick's 0.1 error stays well under this
        double driftThreshold = 0.05;  // ...and over this

        ReplayReport report = TraceReplay.replay(perturbed, perTickThreshold, driftThreshold);

        assertThat(report.firstDivergingTick()).isEmpty();
        assertThat(report.firstDivergingTickError()).isEqualTo(0.0);
        assertThat(report.driftThresholdExceeded()).isTrue();
        assertThat(report.finalDrift()).isCloseTo(0.1, within(1.0e-9));
        assertThat(report.isClean()).isFalse();
    }

    /**
     * The summed per-tick error is reported but bounded by nothing, and it is a different number
     * from the drift: perturbing every tick by the same {@code 0.1} leaves the replay ending
     * {@code 0.1} from the recording while the sum reaches {@code 2.5}. Conflating the two is what
     * the earlier revision did — it bounded this sum at {@code 1.0E-4} while calling it the spec's
     * {@code 0.01}-blocks drift figure, two orders of magnitude and one metric apart.
     */
    @Test
    void theSummedTickErrorIsReportedSeparatelyFromTheFinalDrift() {
        int tickCount = 25;
        TraceFixture clean = generateFixture(seed(), constantInputs(tickCount, 0.0f, -20.0f), FREE_FLIGHT, List.of());

        TraceFixture perturbed = clean;
        for (int i = 1; i <= tickCount; i++) {
            perturbed = withTick(perturbed, i, withPosition(perturbed.ticks().get(i), 0.1));
        }

        ReplayReport report = TraceReplay.replay(perturbed, 0.5, 1000.0);

        assertThat(report.finalDrift()).isCloseTo(0.1, within(1.0e-9));
        assertThat(report.summedTickError()).isCloseTo(tickCount * 0.1, within(1.0e-9));
        assertThat(report.driftThresholdExceeded()).isFalse();
        assertThat(report.isClean()).isTrue();
    }

    // ---- the velocity error, and why there is no per-step attribution -----------------------
    //
    // TraceReplay used to also try naming which ElytraStep a divergence belonged to. Measured
    // against realistically-shaped fixtures, that attribution tracked the sign and magnitude of
    // whatever perturbed the recording, not its cause — DRAG only scales velocity by ~1%, so once a
    // divergence reached roughly that size relative to the velocity itself, an unrelated earlier
    // step's output would coincidentally sit closer to the recording than DRAG's own, and get named
    // instead. See TraceReplay's class javadoc for the full account. What remains is the velocity
    // error itself: how far the simulated post-restitution velocity sits from the recorded one, with
    // no claim about which step produced the gap.

    @Test
    void aGenuineVelocityDivergenceIsReportedAsANonZeroVelocityError() {
        TraceFixture clean = generateFixture(seed(), constantInputs(10, 0.0f, -20.0f), FREE_FLIGHT, List.of());
        int perturbedTick = 4;

        TraceFixture.Tick original = clean.ticks().get(perturbedTick);
        Vec3 recordedVelocity = new Vec3(original.velX() + 0.01, original.velY() + 0.01, original.velZ() - 0.01);
        TraceFixture.Tick replacement = withVelocity(withPosition(original, 0.25), recordedVelocity);
        TraceFixture perturbed = withTick(clean, perturbedTick, replacement);

        ReplayReport report = TraceReplay.replay(perturbed, 1.0E-9, 1000.0);

        assertThat(report.firstDivergingTick()).hasValue(perturbedTick);
        assertThat(report.firstDivergingTickVelocityError()).isGreaterThan(0.0);
    }

    /**
     * A tiny position-only nudge (velocity left exactly as recorded) is enough to force the replay
     * to evaluate and report a velocity error at a chosen tick, without introducing any real
     * velocity divergence — so the reported error must come out at exactly {@code 0.0} in free
     * flight, where there is no restitution to confuse it with.
     */
    @Test
    void theVelocityErrorIsZeroWhenOnlyPositionWasNudgedInFreeFlight() {
        TraceFixture clean = generateFixture(seed(), constantInputs(10, 0.0f, -20.0f), FREE_FLIGHT, List.of());
        int tick = 4;
        TraceFixture forced = withTick(clean, tick, withPosition(clean.ticks().get(tick), 1.0E-7));

        ReplayReport report = TraceReplay.replay(forced, 1.0E-9, 1000.0);

        assertThat(report.firstDivergingTick()).hasValue(tick);
        assertThat(report.firstDivergingTickVelocityError()).isEqualTo(0.0);
    }

    /**
     * The case the reviewer measured directly: comparing against {@code velocityAfter(DRAG)} (the
     * pre-restitution step output) instead of {@code state.velocity()} (post-restitution) reported
     * a velocity error of {@code 0.2848} on this exact fixture, entirely from the restitution gap on
     * the landing tick — a completely correct simulation, reported as if its velocity were wrong.
     * Forcing evaluation at the landing tick the same way as the free-flight test above (position
     * nudged, velocity untouched) must report {@code 0.0} here too, precisely because the tick
     * involves a real collision and restitution.
     */
    @Test
    void theVelocityErrorIsZeroOnACleanLandingTickNotTheRestitutionGap() {
        TraceFixture clean = landingFixture();
        int landingTick = clean.ticks().size() - 1;
        assertThat(clean.ticks().get(landingTick).onGround()).isTrue();

        TraceFixture forced = withTick(clean, landingTick, withPosition(clean.ticks().get(landingTick), 1.0E-7));

        ReplayReport report = TraceReplay.replay(forced, 1.0E-9, 1000.0);

        assertThat(report.firstDivergingTick()).hasValue(landingTick);
        assertThat(report.firstDivergingTickVelocityError()).isEqualTo(0.0);
    }

    // ---- malformed / empty fixtures fail with a domain exception -----------------------------

    @Test
    void aFixtureWithNoTicksFailsWithADomainExceptionRatherThanBeingConstructed() {
        TraceFixture.Metadata metadata = new TraceFixture.Metadata("26.2", "synthetic", GRAVITY, 1, List.of());

        assertThatThrownBy(() -> new TraceFixture(metadata, List.of()))
                .isInstanceOf(InvalidTraceFixtureException.class);
    }

    @Test
    void aFixtureWithANullTickListFailsWithADomainExceptionNotANullPointerException() {
        TraceFixture.Metadata metadata = new TraceFixture.Metadata("26.2", "synthetic", GRAVITY, 1, List.of());

        assertThatThrownBy(() -> new TraceFixture(metadata, null))
                .isInstanceOf(InvalidTraceFixtureException.class);
    }

    @Test
    void replayingANullFixtureFailsWithADomainExceptionNotANullPointerException() {
        assertThatThrownBy(() -> TraceReplay.replay(null)).isInstanceOf(InvalidTraceFixtureException.class);
    }

    @Test
    void aFixtureWhoseMetadataIsMissingItsWorldSliceFailsWithADomainException() {
        assertThatThrownBy(() -> new TraceFixture.Metadata("26.2", "synthetic", GRAVITY, 1, null))
                .isInstanceOf(InvalidTraceFixtureException.class)
                .hasMessageContaining("worldSlice");
    }

    /**
     * A missing {@code worldSlice} key deserializes to {@code null}, same as leaving it out of a
     * hand-built {@link TraceFixture.Metadata}. An explicit {@code []} must still be accepted — that
     * is a genuine free-flight recording, not a malformed one.
     */
    @Test
    void loadingJsonWithAMissingWorldSliceFieldFailsWithADomainExceptionNotSilentlyEmptyWorld() {
        String json = """
                {"metadata":{"minecraftVersion":"26.2","profile":"p","gravity":0.08,"formatVersion":1},
                 "ticks":[{"index":0,"posX":0,"posY":0,"posZ":0,"velX":0,"velY":0,"velZ":0,
                           "yaw":0,"pitch":0,"onGround":false,"fireworkBoostActive":false,
                           "fireworkTicksRemaining":0}]}
                """;

        assertThatThrownBy(() -> TraceFixtureLoader.fromJson(json))
                .isInstanceOf(InvalidTraceFixtureException.class)
                .hasMessageContaining("worldSlice");
    }

    @Test
    void loadingBlankJsonFailsWithADomainException() {
        assertThatThrownBy(() -> TraceFixtureLoader.fromJson("")).isInstanceOf(InvalidTraceFixtureException.class);
        assertThatThrownBy(() -> TraceFixtureLoader.fromJson(null)).isInstanceOf(InvalidTraceFixtureException.class);
    }

    @Test
    void loadingSyntacticallyInvalidJsonFailsWithADomainExceptionNotAGsonException() {
        assertThatThrownBy(() -> TraceFixtureLoader.fromJson("{ this is not json"))
                .isInstanceOf(InvalidTraceFixtureException.class);
    }

    @Test
    void loadingJsonMissingEveryFieldFailsWithADomainExceptionNotANullPointerException() {
        assertThatThrownBy(() -> TraceFixtureLoader.fromJson("{}"))
                .isInstanceOf(InvalidTraceFixtureException.class)
                .hasMessage("a trace fixture must carry metadata");
    }

    /**
     * Reproduces the exact defect the reviewer measured: without unwrapping Gson's own wrapper
     * exception, this surfaced as {@code "fixture JSON could not be parsed: Failed to invoke
     * constructor '...Metadata(...)' with args [26.2, p, -1.0, 1, []]"} — the actual reason
     * ({@code "gravity must be finite and > 0, was -1.0"}) discarded along with its stack. A loader
     * whose only job is diagnosing broken fixtures cannot lose that message; this pins that the
     * original {@link TraceFixture.Metadata} validation message survives unchanged, and that when a
     * message is rebuilt instead (the JSON-syntax-error path), the original exception is at least
     * chained as the cause rather than discarded.
     */
    @Test
    void loadingJsonThatFailsFixtureValidationPreservesTheOriginalValidationMessage() {
        String json = """
                {"metadata":{"minecraftVersion":"26.2","profile":"p","gravity":-1.0,"formatVersion":1,"worldSlice":[]},
                 "ticks":[{"index":0,"posX":0,"posY":0,"posZ":0,"velX":0,"velY":0,"velZ":0,
                           "yaw":0,"pitch":0,"onGround":false,"fireworkBoostActive":false,
                           "fireworkTicksRemaining":0}]}
                """;

        assertThatThrownBy(() -> TraceFixtureLoader.fromJson(json))
                .isInstanceOf(InvalidTraceFixtureException.class)
                .hasMessage("gravity must be finite and > 0, was -1.0");
    }

    @Test
    void loadingSyntacticallyInvalidJsonChainsTheOriginalExceptionAsTheCause() {
        assertThatThrownBy(() -> TraceFixtureLoader.fromJson("{ this is not json"))
                .isInstanceOf(InvalidTraceFixtureException.class)
                .hasMessageContaining("fixture JSON could not be parsed")
                .cause().isNotNull();
    }

    // ---- TraceReplay validates its own arguments, not just the fixture ------------------------
    //
    // A bad threshold is a defect in the call, not in the fixture, so it fails with
    // InvalidReplayThresholdException rather than InvalidTraceFixtureException.

    @Test
    void replayingWithANonFiniteThresholdFailsWithAThresholdExceptionRatherThanSilentlyReportingClean() {
        TraceFixture clean = generateFixture(seed(), constantInputs(5, 0.0f, -20.0f), FREE_FLIGHT, List.of());

        assertThatThrownBy(() -> TraceReplay.replay(clean, Double.NaN, 1000.0))
                .isInstanceOf(InvalidReplayThresholdException.class);
        assertThatThrownBy(() -> TraceReplay.replay(clean, 0.01, Double.NaN))
                .isInstanceOf(InvalidReplayThresholdException.class);
    }

    @Test
    void replayingWithANegativeThresholdFailsWithAThresholdException() {
        TraceFixture clean = generateFixture(seed(), constantInputs(5, 0.0f, -20.0f), FREE_FLIGHT, List.of());

        assertThatThrownBy(() -> TraceReplay.replay(clean, -0.01, 1000.0))
                .isInstanceOf(InvalidReplayThresholdException.class);
        assertThatThrownBy(() -> TraceReplay.replay(clean, 0.01, -1000.0))
                .isInstanceOf(InvalidReplayThresholdException.class);
    }

    // ---- RecordedCollisionSpace filters on the queried region ---------------------------------

    @Test
    void filtersToOnlyTheBlocksIntersectingTheQueriedRegion() {
        TraceFixture.BlockBox nearby = new TraceFixture.BlockBox(-1, -1, -1, 1, 1, 1);
        TraceFixture.BlockBox faraway = new TraceFixture.BlockBox(500, 500, 500, 501, 501, 501);
        RecordedCollisionSpace space = new RecordedCollisionSpace(List.of(nearby, faraway));

        List<Aabb> result = space.boxesIntersecting(new Aabb(new Vec3(-0.5, -0.5, -0.5), new Vec3(0.5, 0.5, 0.5)));

        assertThat(result).containsExactly(new Aabb(new Vec3(-1, -1, -1), new Vec3(1, 1, 1)));
    }

    @Test
    void anEmptyWorldSliceIntersectsNothing() {
        RecordedCollisionSpace space = new RecordedCollisionSpace(List.of());

        assertThat(space.boxesIntersecting(new Aabb(Vec3.ZERO, new Vec3(1, 1, 1)))).isEmpty();
    }
}
