package net.elytrarace.voyager.physics.trace;

import net.elytrarace.voyager.api.math.Aabb;
import net.elytrarace.voyager.api.math.Vec3;
import net.elytrarace.voyager.api.physics.CollisionSpace;
import net.elytrarace.voyager.api.physics.FlightInput;
import net.elytrarace.voyager.api.physics.FlightState;
import net.elytrarace.voyager.physics.ElytraSimulator;
import net.elytrarace.voyager.physics.TickTrace;
import net.elytrarace.voyager.physics.step.ElytraStep;
import net.elytrarace.voyager.physics.trace.TraceReplay.ReplayReport;
import net.elytrarace.voyager.physics.trace.exception.InvalidTraceFixtureException;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Proves the trace replay harness against synthetic fixtures generated by running {@link
 * ElytraSimulator} itself, since no real Vanilla recording exists until E2a completes (see
 * {@code docs/superpowers/plans/2026-09-10-e2a-trace-recorder.md}). A fixture built this way and
 * replayed with zero divergence proves the harness is correct before it is ever pointed at a real
 * recording — a later red trace then means the physics port is wrong, not that the harness might
 * be.
 */
class TraceReplayTest {

    /**
     * Deliberately not Vanilla's 0.08 default: a replay that hardcodes 0.08 instead of reading
     * {@link TraceFixture.Metadata#gravity()} diverges from every fixture built with this value.
     */
    private static final double GRAVITY = 0.05;

    private static final CollisionSpace FREE_FLIGHT = CollisionSpace.empty();

    // ---- fixture construction helpers --------------------------------------------------------

    private static FlightState seed() {
        return new FlightState(new Vec3(0, 100, 0), new Vec3(0.3, -0.2, 0.5), 0.0f, -20.0f, false);
    }

    private static List<FlightInput> constantInputs(int count, float yaw, float pitch) {
        List<FlightInput> inputs = new ArrayList<>();
        for (int i = 0; i < count; i++) {
            inputs.add(new FlightInput(yaw, pitch, false, 0, GRAVITY));
        }
        return inputs;
    }

    private static TraceFixture.Tick tickOf(FlightState state, boolean boostActive, int boostTicks) {
        return new TraceFixture.Tick(
                0,
                state.position().x(), state.position().y(), state.position().z(),
                state.velocity().x(), state.velocity().y(), state.velocity().z(),
                state.yaw(), state.pitch(),
                state.onGround(),
                boostActive, boostTicks);
    }

    private static TraceFixture.Tick withIndex(TraceFixture.Tick tick, int index) {
        return new TraceFixture.Tick(
                index,
                tick.posX(), tick.posY(), tick.posZ(),
                tick.velX(), tick.velY(), tick.velZ(),
                tick.yaw(), tick.pitch(),
                tick.onGround(), tick.fireworkBoostActive(), tick.fireworkTicksRemaining());
    }

    /** Runs {@link ElytraSimulator#tick} forward and records every tick in fixture format. */
    private static TraceFixture generateFixture(
            FlightState seed, List<FlightInput> inputs, CollisionSpace space, List<TraceFixture.BlockBox> worldSlice) {
        List<TraceFixture.Tick> ticks = new ArrayList<>();
        ticks.add(withIndex(tickOf(seed, false, 0), 0));

        FlightState state = seed;
        for (int i = 0; i < inputs.size(); i++) {
            state = ElytraSimulator.tick(state, inputs.get(i), space);
            ticks.add(withIndex(tickOf(state, inputs.get(i).fireworkBoostActive(), inputs.get(i).fireworkTicksRemaining()), i + 1));
        }

        TraceFixture.Metadata metadata = new TraceFixture.Metadata("26.2", "synthetic", GRAVITY, 1, worldSlice);
        return new TraceFixture(metadata, ticks);
    }

    private static FlightState stateOf(TraceFixture.Tick tick) {
        return new FlightState(
                new Vec3(tick.posX(), tick.posY(), tick.posZ()),
                new Vec3(tick.velX(), tick.velY(), tick.velZ()),
                tick.yaw(), tick.pitch(), tick.onGround());
    }

    private static TraceFixture.Tick withPosition(TraceFixture.Tick tick, double dx) {
        return new TraceFixture.Tick(
                tick.index(),
                tick.posX() + dx, tick.posY(), tick.posZ(),
                tick.velX(), tick.velY(), tick.velZ(),
                tick.yaw(), tick.pitch(),
                tick.onGround(), tick.fireworkBoostActive(), tick.fireworkTicksRemaining());
    }

    private static TraceFixture.Tick withVelocity(TraceFixture.Tick tick, Vec3 velocity) {
        return new TraceFixture.Tick(
                tick.index(),
                tick.posX(), tick.posY(), tick.posZ(),
                velocity.x(), velocity.y(), velocity.z(),
                tick.yaw(), tick.pitch(),
                tick.onGround(), tick.fireworkBoostActive(), tick.fireworkTicksRemaining());
    }

    private static TraceFixture withTick(TraceFixture fixture, int index, TraceFixture.Tick replacement) {
        List<TraceFixture.Tick> ticks = new ArrayList<>(fixture.ticks());
        ticks.set(index, replacement);
        return new TraceFixture(fixture.metadata(), ticks);
    }

    // ---- clean replay --------------------------------------------------------------------------

    @Test
    void aSyntheticFixtureGeneratedFromTheSimulatorReplaysWithZeroDivergence() {
        TraceFixture fixture = generateFixture(seed(), constantInputs(30, 0.0f, -20.0f), FREE_FLIGHT, List.of());

        ReplayReport report = TraceReplay.replay(fixture);

        assertThat(report.isClean()).isTrue();
        assertThat(report.firstDivergingTick()).isEmpty();
        assertThat(report.divergingStep()).isEmpty();
        assertThat(report.cumulativeError()).isEqualTo(0.0);
        assertThat(report.cumulativeThresholdExceeded()).isFalse();
    }

    @Test
    void aSyntheticFixtureWithCollisionAgainstAFloorReplaysWithZeroDivergence() {
        List<TraceFixture.BlockBox> worldSlice = List.of(new TraceFixture.BlockBox(-64, -1, -64, 64, 0, 64));
        CollisionSpace floor = region -> List.of(new Aabb(new Vec3(-64, -1, -64), new Vec3(64, 0, 64)));
        FlightState fallingSeed = new FlightState(new Vec3(0, 2, 0), new Vec3(0, -0.5, 0.2), 0.0f, 0.0f, false);

        TraceFixture fixture = generateFixture(fallingSeed, constantInputs(15, 0.0f, 0.0f), floor, worldSlice);

        ReplayReport report = TraceReplay.replay(fixture);

        assertThat(report.isClean()).isTrue();
        assertThat(report.cumulativeError()).isEqualTo(0.0);
    }

    @Test
    void theJsonRoundTripPreservesASyntheticFixtureAndStillReplaysClean() {
        TraceFixture fixture = generateFixture(seed(), constantInputs(10, 0.0f, -20.0f), FREE_FLIGHT, List.of());

        String json = TraceFixtureLoader.toJson(fixture);
        TraceFixture restored = TraceFixtureLoader.fromJson(json);

        assertThat(restored).isEqualTo(fixture);
        assertThat(TraceReplay.replay(restored).isClean()).isTrue();
    }

    // ---- naming the diverging tick ---------------------------------------------------------

    @Test
    void aPerturbedTickIsNamedRatherThanAnArbitraryOne() {
        TraceFixture clean = generateFixture(seed(), constantInputs(20, 0.0f, -20.0f), FREE_FLIGHT, List.of());
        int perturbedTick = 8;
        TraceFixture perturbed = withTick(clean, perturbedTick, withPosition(clean.ticks().get(perturbedTick), 0.25));

        ReplayReport report = TraceReplay.replay(perturbed, 0.01, 1000.0);

        assertThat(report.firstDivergingTick()).hasValue(perturbedTick);
    }

    @Test
    void theFirstDivergingTickIsReportedEvenWhenALaterTickDivergesMore() {
        TraceFixture clean = generateFixture(seed(), constantInputs(20, 0.0f, -20.0f), FREE_FLIGHT, List.of());
        double threshold = 0.01;
        int earlyTick = 5;
        int laterTick = 15;

        TraceFixture perturbed = withTick(clean, earlyTick, withPosition(clean.ticks().get(earlyTick), threshold + 0.001));
        perturbed = withTick(perturbed, laterTick, withPosition(perturbed.ticks().get(laterTick), threshold + 5.0));

        ReplayReport report = TraceReplay.replay(perturbed, threshold, 1000.0);

        assertThat(report.firstDivergingTick()).hasValue(earlyTick);
        assertThat(report.firstDivergingTickError()).isLessThan(5.0);
    }

    // ---- per-tick threshold boundary --------------------------------------------------------

    /**
     * Pins the boundary just below the threshold rather than exactly at it: the recorded position
     * here is built by adding a double to a value already computed by the simulator (position
     * magnitude ~100), and IEEE 754 addition of two such values is not guaranteed to round-trip
     * back to an error of exactly {@code threshold} on subtraction — the last bit or two can go
     * either way. A margin many orders of magnitude past that rounding noise (~1e-14 at this
     * magnitude) still pins the boundary tightly without the test depending on bit-exact rounding.
     */
    @Test
    void divergenceJustBelowThePerTickThresholdIsNotReported() {
        TraceFixture clean = generateFixture(seed(), constantInputs(10, 0.0f, -20.0f), FREE_FLIGHT, List.of());
        int tick = 4;
        double threshold = 0.25;
        TraceFixture perturbed = withTick(clean, tick, withPosition(clean.ticks().get(tick), threshold - 1.0E-9));

        ReplayReport report = TraceReplay.replay(perturbed, threshold, 1000.0);

        assertThat(report.firstDivergingTick()).isEmpty();
    }

    @Test
    void divergenceJustAboveThePerTickThresholdIsReportedAsAFailure() {
        TraceFixture clean = generateFixture(seed(), constantInputs(10, 0.0f, -20.0f), FREE_FLIGHT, List.of());
        int tick = 4;
        double threshold = 0.25;
        TraceFixture perturbed = withTick(clean, tick, withPosition(clean.ticks().get(tick), threshold + 1.0E-9));

        ReplayReport report = TraceReplay.replay(perturbed, threshold, 1000.0);

        assertThat(report.firstDivergingTick()).hasValue(tick);
    }

    // ---- cumulative error is independent of the per-tick bound ------------------------------

    @Test
    void cumulativeErrorIsReportedSeparatelyFromPerTickError() {
        TraceFixture clean = generateFixture(seed(), constantInputs(20, 0.0f, -20.0f), FREE_FLIGHT, List.of());

        ReplayReport clean1 = TraceReplay.replay(clean);
        assertThat(clean1.cumulativeError()).isEqualTo(0.0);
        assertThat(clean1.firstDivergingTickError()).isEqualTo(0.0);
    }

    @Test
    void aReplayStayingUnderThePerTickBoundButOverTheCumulativeBoundIsStillReported() {
        int tickCount = 25;
        TraceFixture clean = generateFixture(seed(), constantInputs(tickCount, 0.0f, -20.0f), FREE_FLIGHT, List.of());

        TraceFixture perturbed = clean;
        for (int i = 1; i <= tickCount; i++) {
            perturbed = withTick(perturbed, i, withPosition(perturbed.ticks().get(i), 0.1));
        }

        double perTickThreshold = 0.5; // each tick's 0.1 error stays well under this
        double cumulativeThreshold = 2.0; // 25 * 0.1 == 2.5, over this

        ReplayReport report = TraceReplay.replay(perturbed, perTickThreshold, cumulativeThreshold);

        assertThat(report.firstDivergingTick()).isEmpty();
        assertThat(report.cumulativeThresholdExceeded()).isTrue();
        assertThat(report.cumulativeError()).isGreaterThan(cumulativeThreshold);
        assertThat(report.isClean()).isFalse();
    }

    // ---- naming the diverging step -----------------------------------------------------------

    @Test
    void theDivergingStepIsAttributableToWhicheverStepTheRecordedVelocityStoppedMatching() {
        TraceFixture clean = generateFixture(seed(), constantInputs(10, 0.0f, -20.0f), FREE_FLIGHT, List.of());
        int perturbedTick = 4;

        TickTrace trace = recomputeTick(clean, perturbedTick);
        Vec3 stoppedAtDirectionAlignment = trace.velocityAfter().get(ElytraStep.DIRECTION_ALIGNMENT);

        TraceFixture.Tick original = clean.ticks().get(perturbedTick);
        TraceFixture.Tick replacement = withVelocity(withPosition(original, 0.25), stoppedAtDirectionAlignment);
        TraceFixture perturbed = withTick(clean, perturbedTick, replacement);

        ReplayReport report = TraceReplay.replay(perturbed, 1.0E-9, 1000.0);

        assertThat(report.firstDivergingTick()).hasValue(perturbedTick);
        assertThat(report.divergingStep()).hasValue(ElytraStep.DRAG);
    }

    @Test
    void aDifferentStoppingPointNamesADifferentStepRatherThanTheSameOneEveryTime() {
        TraceFixture clean = generateFixture(seed(), constantInputs(10, 0.0f, -20.0f), FREE_FLIGHT, List.of());
        int perturbedTick = 4;

        TickTrace trace = recomputeTick(clean, perturbedTick);
        Vec3 stoppedAtUpwardPitchBoost = trace.velocityAfter().get(ElytraStep.UPWARD_PITCH_BOOST);

        TraceFixture.Tick original = clean.ticks().get(perturbedTick);
        TraceFixture.Tick replacement = withVelocity(withPosition(original, 0.25), stoppedAtUpwardPitchBoost);
        TraceFixture perturbed = withTick(clean, perturbedTick, replacement);

        ReplayReport report = TraceReplay.replay(perturbed, 1.0E-9, 1000.0);

        assertThat(report.firstDivergingTick()).hasValue(perturbedTick);
        assertThat(report.divergingStep()).hasValue(ElytraStep.DIRECTION_ALIGNMENT);
    }

    /** Recomputes the traced tick that produced {@code clean.ticks().get(tickIndex)}, white-box. */
    private static TickTrace recomputeTick(TraceFixture clean, int tickIndex) {
        FlightState previous = stateOf(clean.ticks().get(tickIndex - 1));
        TraceFixture.Tick recorded = clean.ticks().get(tickIndex);
        FlightInput input = new FlightInput(
                recorded.yaw(), recorded.pitch(),
                recorded.fireworkBoostActive(), recorded.fireworkTicksRemaining(), GRAVITY);
        return ElytraSimulator.tickTraced(previous, input, FREE_FLIGHT);
    }

    // ---- malformed / empty fixtures fail with a domain exception -----------------------------

    @Test
    void aFixtureWithNoTicksFailsWithADomainExceptionRatherThanBeingConstructed() {
        TraceFixture.Metadata metadata = new TraceFixture.Metadata("26.2", "synthetic", GRAVITY, 1, List.of());

        assertThatThrownBy(() -> new TraceFixture(metadata, List.of()))
                .isInstanceOf(InvalidTraceFixtureException.class);
    }

    @Test
    void aFixtureWithANullTickListFailsWithADomainExceptionNotANullPointerException() {
        TraceFixture.Metadata metadata = new TraceFixture.Metadata("26.2", "synthetic", GRAVITY, 1, List.of());

        assertThatThrownBy(() -> new TraceFixture(metadata, null))
                .isInstanceOf(InvalidTraceFixtureException.class);
    }

    @Test
    void replayingANullFixtureFailsWithADomainExceptionNotANullPointerException() {
        assertThatThrownBy(() -> TraceReplay.replay(null)).isInstanceOf(InvalidTraceFixtureException.class);
    }

    @Test
    void loadingBlankJsonFailsWithADomainException() {
        assertThatThrownBy(() -> TraceFixtureLoader.fromJson("")).isInstanceOf(InvalidTraceFixtureException.class);
        assertThatThrownBy(() -> TraceFixtureLoader.fromJson(null)).isInstanceOf(InvalidTraceFixtureException.class);
    }

    @Test
    void loadingSyntacticallyInvalidJsonFailsWithADomainExceptionNotAGsonException() {
        assertThatThrownBy(() -> TraceFixtureLoader.fromJson("{ this is not json"))
                .isInstanceOf(InvalidTraceFixtureException.class);
    }

    @Test
    void loadingJsonMissingEveryFieldFailsWithADomainExceptionNotANullPointerException() {
        assertThatThrownBy(() -> TraceFixtureLoader.fromJson("{}"))
                .isInstanceOf(InvalidTraceFixtureException.class);
    }

    // ---- RecordedCollisionSpace filters on the queried region ---------------------------------

    @Test
    void filtersToOnlyTheBlocksIntersectingTheQueriedRegion() {
        TraceFixture.BlockBox nearby = new TraceFixture.BlockBox(-1, -1, -1, 1, 1, 1);
        TraceFixture.BlockBox faraway = new TraceFixture.BlockBox(500, 500, 500, 501, 501, 501);
        RecordedCollisionSpace space = new RecordedCollisionSpace(List.of(nearby, faraway));

        List<Aabb> result = space.boxesIntersecting(new Aabb(new Vec3(-0.5, -0.5, -0.5), new Vec3(0.5, 0.5, 0.5)));

        assertThat(result).containsExactly(new Aabb(new Vec3(-1, -1, -1), new Vec3(1, 1, 1)));
    }

    @Test
    void anEmptyWorldSliceIntersectsNothing() {
        RecordedCollisionSpace space = new RecordedCollisionSpace(List.of());

        assertThat(space.boxesIntersecting(new Aabb(Vec3.ZERO, new Vec3(1, 1, 1)))).isEmpty();
    }
}
