sqlConfig {
    jdbcUrl = "jdbc:h2:./plugins/Voyager/game"
    driverClassName = "org.h2.Driver"
    username = ""
    password = ""
    maximumPoolSize = 10
}

cupConfiguration {
    minPlayerSize = 2
    playerSize = 10
    cupName = "TeamTesting"
}

lobbyConfiguration {
    worldName = "world"
    x = 0
    y = 0
    z = 0
    yaw = 0.0
    pitch = 0.0
}