name: Build
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    if: github.repository_owner == 'OneLiteFeatherNET'
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      ONELITEFEATHER_MAVEN_USERNAME: ${{ secrets.ONELITEFEATHER_MAVEN_USERNAME }}
      ONELITEFEATHER_MAVEN_PASSWORD: ${{ secrets.ONELITEFEATHER_MAVEN_PASSWORD }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - name: Build
        run: ./gradlew clean build

      - name: Upload JaCoCo Reports
        if: always() && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-reports
          path: '**/build/reports/jacoco/**'
          retention-days: 14

      - name: Upload Shadow JAR
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: shadow-jar
          path: server/build/libs/*.jar
          if-no-files-found: warn
          retention-days: 14
