name: Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions:
  contents: read
  actions: read

jobs:
  build:
    if: github.repository_owner == 'OneLiteFeatherNET'
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Java
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@48b5f213c81028ace310571dc5ec0fbbca0b2947 # v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.event_name == 'pull_request' }}

      - name: Build
        run: ./gradlew build
        env:
          ONELITEFEATHER_MAVEN_USERNAME: ${{ secrets.ONELITEFEATHER_MAVEN_USERNAME }}
          ONELITEFEATHER_MAVEN_PASSWORD: ${{ secrets.ONELITEFEATHER_MAVEN_PASSWORD }}

      - name: Upload JaCoCo reports
        if: always() && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: jacoco-reports
          path: '**/build/reports/jacoco/**'
          retention-days: 14
          if-no-files-found: ignore

      - name: Upload Shadow JAR
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: shadow-jar
          path: server/build/libs/*.jar
          if-no-files-found: warn
          retention-days: 14
